# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='isDynamic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userevent',
            name='isDynamic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='eventLength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='eventLength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
